Selenium8

diff --git a/.github/workflows/selenium.yaml b/.github/workflows/selenium.yaml
--- a/.github/workflows/selenium.yaml
+++ b/.github/workflows/selenium.yaml
@@ -62,7 +62,7 @@ jobs:
 
       - name: Verify server is running
         run: |
-          curl -f http://localhost:8080 || { echo "Server failed to start"; exit 1; }
+          curl -f http://localhost:80 || { echo "Server failed to start"; exit 1; }
 
       - name: Run Selenium tests
         run: node .github/selenium.test.js
